apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: registry-nodeport
spec:
  type: NodePort
  ports:
    - name: repo
      port: 5000
      nodePort: 32396
    - name: debug
      port: 5001
  selector:
    name: registry-app
