apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kube-system
  name: registry-config
data:
  config: |
    version: 0.1
    log:
      level: info
      formatter: text
      fields:
        service: registry
        environment: development
    storage:
        filesystem:
            rootdirectory: /registry
        delete:
            enabled: true
        maintenance:
            uploadpurging:
                enabled: true
                age: 168h
                interval: 24h
                dryrun: false
    auth:
      htpasswd:
        realm: basic-realm
        path: /etc/docker/registry/reg.htpasswd
    http:
        addr: :5000
        secret: asecret_for_local_development
        debug:
            addr: :5001
        headers:
            X-Content-Type-Options: [nosniff]
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3

  htpasswd: |
    atlab:PWroKyYTybPqs
    pandora:W5/zAxSsFINgM