apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: kube-system
  name: data-registry-pv
  labels:
    type: data-registry
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/registry
