apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: kube-system
  name: registry-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  selector:
    matchLabels:
      type: data-registry